#!/usr/bin/env node
// Build dist/motomation-design.md: the whole skill in one file for chat tools
// (ChatGPT, Grok, Google AI Studio, Gemini, v0, Lovable, Claude Projects) that can't install skills.
import { readFileSync, writeFileSync, readdirSync, mkdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const SKILL = join(ROOT, "skills/asfakulsiam-motomation-design");
const version = readFileSync(join(SKILL, "VERSION"), "utf8").trim();

const ORDER = ["SKILL.md", "thinking", "invention", "structures", "principles", "motion", "signatures", "styles", "categories", "craft", "gates", "commands", "adapters", "references", "templates"];
const walk = (p) => statSync(p).isDirectory() ? readdirSync(p).sort().flatMap((f) => walk(join(p, f))) : [p];

const parts = [
  `# Motomation Design v${version}: single-file edition`,
  "",
  "> By asfakulsiam · MIT · https://github.com/asfakulsiam/asfakulsiam-motomation-design",
  "> Generated by `scripts/build-dist.mjs`. Do not edit by hand.",
  "> For chat tools without a shell: wherever the skill says \"run scripts/…\", use the data tables at the end of this file instead",
  "> (see \"Without a shell\" in adapters/platforms). Always choose rows deliberately, never the first row.",
  "",
];

for (const entry of ORDER) {
  for (const file of walk(join(SKILL, entry)).filter((f) => f.endsWith(".md"))) {
    let text = readFileSync(file, "utf8");
    text = text.replace(/^---\n[\s\S]*?\n---\n/, "");             // drop front-matter
    text = text.replace(/^(#{1,5}) /gm, "#$1 ");                  // demote headings one level
    parts.push(`\n---\n\n<!-- file: ${relative(SKILL, file)} -->\n`, text.trim(), "");
  }
}

parts.push("\n---\n\n## Data tables (CSV)\n");
for (const f of readdirSync(join(SKILL, "data")).sort()) {
  parts.push(`### data/${f}\n`, "```csv", readFileSync(join(SKILL, "data", f), "utf8").trim(), "```", "");
}

mkdirSync(join(ROOT, "dist"), { recursive: true });
const out = parts.join("\n") + "\n";
const target = join(ROOT, "dist/motomation-design.md");
if (process.argv.includes("--check")) {
  let current = ""; try { current = readFileSync(target, "utf8"); } catch {}
  if (current !== out) { console.error("dist/motomation-design.md is out of date. Run: node scripts/build-dist.mjs"); process.exit(1); }
  console.log("dist is up to date");
} else {
  writeFileSync(target, out);
  console.log(`Wrote dist/motomation-design.md (${(out.length / 1024).toFixed(0)} KB)`);
}
